"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(563(1zyes$586s&i=(nwgo=t-n#ke2xez+o*n7rin5#titvwy"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "mptt",
    "ckeditor",
    "ckeditor_uploader",
    "phonenumber_field",
    "azbankgateways",
    "django_jalali",
    # Local apps
    "apps.accounts.apps.AccountsConfig",
    "apps.blog.apps.BlogConfig",
    "apps.subscriptions.apps.SubscriptionsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432", cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "accounts.CustomUser"

APPEND_SLASH = True


# تنظیمات فایل‌های استاتیک
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# اگر از پوشه‌های استاتیک اضافی استفاده می‌کنید:
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# تنظیمات فایل‌های رسانه‌ای (اگر استفاده می‌کنید)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# CKEditor Configuration

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    "default": {
        "toolbar": "full",
        "height": 300,
        "width": "full",
        "extraPlugins": ",".join(
            [
                "uploadimage",
                "uploadwidget",
                "iframe",
                "dialogui",
                "dialog",
                "video",
            ]
        ),
        "toolbar_Custom": [
            ["Bold", "Italic", "Underline"],
            [
                "NumberedList",
                "BulletedList",
                "-",
                "Outdent",
                "Indent",
                "-",
                "JustifyLeft",
                "JustifyCenter",
                "JustifyRight",
                "JustifyBlock",
            ],
            ["Link", "Unlink"],
            ["Image", "Video", "Flash", "Table", "HorizontalRule"],
            ["TextColor", "BGColor"],
            ["Smiley", "SpecialChar"],
            ["Source"],
        ],
        "toolbar": "Custom",
        "allowedContent": True,
        "video_detector_width": "640",
        "video_detector_height": "480",
    },
}

# CKEDITOR_ALLOW_NONIMAGE_FILES = False  # فقط اجازه آپلود تصاویر
# CKEDITOR_RESTRICT_BY_USER = True  # محدود کردن آپلود به کاربر فعلی
# CKEDITOR_RESTRICT_BY_DATE = True  # سازماندهی آپلودها بر اساس تاریخ

# Phone number field settings
PHONENUMBER_DEFAULT_REGION = "IR"

# AZ Iranian Bank Gateways settings
# AZ_IRANIAN_BANK_GATEWAYS = {
#     'GATEWAYS': {
#         'ZARINPAL': {
#             'MERCHANT_CODE': '123456789012345678901234567890123456',  # مرچنت کد تست زرین‌پال
#             'SANDBOX': True,  # فعال کردن حالت sandbox
#         },
#     },
#     'IS_SAMPLE_FORM_ENABLE': True,
#     'DEFAULT': 'ZARINPAL',
#     'CURRENCY': 'IRT',  # یا 'IRR' برای ریال
#     'TRACKING_CODE_QUERY_PARAM': 'tc',
#     'TRACKING_CODE_LENGTH': 16,
#     'SETTING_VALUE_READER_CLASS': 'azbankgateways.readers.DefaultReader',
#     'BANK_PRIORITIES': ['ZARINPAL'],
# }

AZ_IRANIAN_BANK_GATEWAYS = {
    "GATEWAYS": {
        "PAYV1": {
            "MERCHANT_CODE": "123456",  # این کد برای sandbox PAYV1 استفاده می‌شود
            "X_SANDBOX": 1,
        },
    },
    "IS_SAMPLE_FORM_ENABLE": True,
    "DEFAULT": "PAYV1",
    "CURRENCY": "IRR",  # یا 'IRT' برای تومان
    "TRACKING_CODE_QUERY_PARAM": "tc",
    "TRACKING_CODE_LENGTH": 16,
}

# Login and Logout URLs
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"


# Security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
